export const INIT_CHARACTERS = "INIT_CHARACTERS";
export const SET_CHARACTERS = "SET_CHARACTERS";
export const FILTER_CHARACTERS = "FILTER_CHARACTERS";
export const INIT_SINGLE_CHARACTER = "INIT_SINGLE_CHARACTER";
export const SET_SINGLE_CHARACTER = "SET_SINGLE_CHARACTER";

export const ADD_FAVOURITES = "ADD_FAVOURITES";
